public with sharing class HelloWorld {
    public integer calcuatorMethod(Integer number1, Integer number2, Integer number3){
    return number1+number2+number3;
    system.debug('commit our changes dude!!');
    integer a;
    }
    public set<Integer> intSet;
    public static void gulMohorNagar(Id accId){
        Account objAcc=new Account();
        objAcc.Id=accId;
        objAcc.Name='Test'+accId;
    }
    public static Contact createContact(Id accId, String contactName){
        Contact objCon=new Contact(Name=contactName, AccountId=accId);
        insert objCon;
        return objCon;
        
    }
}